### ISSUE TITLE
Powernode 1 seems not to report power state and power measurement

### ISSUE THREAD

**Issue by snijplank** [athombv/com.greenwavesystems#13]
All my connected powernodes 1 do not report there power measurement, also when changing the power button manually on the power node it doesn't get noticed by homey.

Greenwave app version: V1.0.3
Homey Version:  V0.10.3

Poll interval 120

**Comment by jghaanstra** [comment]
@snijplank the reporting of the socket status within Homey is dependent of the polling of the devices by Homey. So a manual switch of the socket will not be noticed by Homey straight away but only after polling of the device has taken place.

The reporting of current power usage can be fixed by setting all association groups to '1' (actually only setting association group 3 to '1' should fix that issue).

**Comment by snijplank** [comment]
i can confirm changing the association group works. Thanks!

**Comment by RobinBol** [comment]
I have added association group 3 to P1 and P6 driver. However, it seems that power_meter (kWh) remains empty, the device never sends an update. @jghaanstra can you confirm that this is working for you with association group 3 set to 1?

**Comment by RobinBol** [comment]
Nevermind, it just took a lot of time before the kWh value was updated. Will publish the fix asap!

**Comment by RobinBol** [comment]
Update is published.
